cmd_/root/kernel/elementary/broad/src/wl/sys/wl_iw.o := gcc -Wp,-MD,/root/kernel/elementary/broad/src/wl/sys/.wl_iw.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/media/luismaf/my-passport/Linux/Kernel/elementary/linux-3.14.3/arch/x86/include -Iarch/x86/include/generated  -Iinclude -I/media/luismaf/my-passport/Linux/Kernel/elementary/linux-3.14.3/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/media/luismaf/my-passport/Linux/Kernel/elementary/linux-3.14.3/include/uapi -Iinclude/generated/uapi -include /media/luismaf/my-passport/Linux/Kernel/elementary/linux-3.14.3/include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m64 -mno-mmx -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -DUSE_CFG80211 -I/root/kernel/elementary/broad/src/include -I/root/kernel/elementary/broad/src/common/include -I/root/kernel/elementary/broad/src/wl/sys -I/root/kernel/elementary/broad/src/wl/phy -I/root/kernel/elementary/broad/src/wl/ppr/include -I/root/kernel/elementary/broad/src/shared/bcmwifi/include  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(wl_iw)"  -D"KBUILD_MODNAME=KBUILD_STR(wl)" -c -o /root/kernel/elementary/broad/src/wl/sys/.tmp_wl_iw.o /root/kernel/elementary/broad/src/wl/sys/wl_iw.c

source_/root/kernel/elementary/broad/src/wl/sys/wl_iw.o := /root/kernel/elementary/broad/src/wl/sys/wl_iw.c

deps_/root/kernel/elementary/broad/src/wl/sys/wl_iw.o := \

/root/kernel/elementary/broad/src/wl/sys/wl_iw.o: $(deps_/root/kernel/elementary/broad/src/wl/sys/wl_iw.o)

$(deps_/root/kernel/elementary/broad/src/wl/sys/wl_iw.o):
