cmd_/home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.o := gcc -Wp,-MD,/home/luismaf/kernel/elementary/broad2/src/wl/sys/.wl_iw.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include -I./arch/x86/include -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -m64 -mno-mmx -mno-sse -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -DUSE_CFG80211 -I/home/luismaf/kernel/elementary/broad2/src/include -I/home/luismaf/kernel/elementary/broad2/src/common/include -I/home/luismaf/kernel/elementary/broad2/src/wl/sys -I/home/luismaf/kernel/elementary/broad2/src/wl/phy -I/home/luismaf/kernel/elementary/broad2/src/wl/ppr/include -I/home/luismaf/kernel/elementary/broad2/src/shared/bcmwifi/include  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(wl_iw)"  -D"KBUILD_MODNAME=KBUILD_STR(wl)" -c -o /home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.o /home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.c

source_/home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.o := /home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.c

deps_/home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.o := \

/home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.o: $(deps_/home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.o)

$(deps_/home/luismaf/kernel/elementary/broad2/src/wl/sys/wl_iw.o):
